INSERT INTO T_USER_SPRING (LOGIN,PASS,NB_CONNEXION, ROLE) VALUES ('Marleyb', 'marleyb123', 0,'user');
INSERT INTO T_USER_SPRING (LOGIN,PASS,NB_CONNEXION, ROLE) VALUES ('Charliep', 'charliep123', 0,'user' );
INSERT INTO T_USER_SPRING (LOGIN,PASS,NB_CONNEXION, ROLE) VALUES ('Milesd', 'milesd123', 0,'user');
INSERT INTO T_USER_SPRING (LOGIN,PASS,NB_CONNEXION, ROLE) VALUES ('Keithj', 'keithj123', 0,'user');
INSERT INTO T_USER_SPRING (LOGIN,PASS,NB_CONNEXION, ROLE) VALUES ('Admin', 'admin132', 0,'admin');

   
INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Bonbon', 'Haribo', 0.2);
INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Stylo Bleu', 'Bic', 1);
INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Ramette 80 grs', 'ClaireFontaine', 5);
INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Equerre', 'Castorama', 2);
INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Montre', 'Rolex', 200);
INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Velo', 'Decathlon', 190);

INSERT INTO T_ARTICLE_SPRING (DESCRIPTION, MARQUE, PRIX) VALUES ('Rameur', 'Decathlon', 290);

